In [41]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\ssrin\Workspace\Code\Upright_edu\wk8-sales.csv')

In [42]:
df.head()

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.0,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.0,5,10,1,49.99,credit card
2,3,2022-01-18,2.0,8,3,1,349.99,DEBIT CARD
3,4,2022-01-20,4.0,20,7,1,349.99,Cash
4,5,2022-01-22,5.0,3,15,1,1599.99,CC

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sale_id         40 non-null     int64
 1   date            39 non-null     str
 2   store_id        39 non-null     float64
 3   customer_id     40 non-null     int64
 4   product_id      40 non-null     int64
 5   quantity        40 non-null     int64
 6   total           40 non-null     float64
 7   payment_method  39 non-null     str
dtypes: float64(2), int64(4), str(2)
memory usage: 2.6 KB

In [44]:
df.describe()

         sale_id   store_id  customer_id  product_id   quantity        total
count  40.000000  39.000000    40.000000   40.000000  40.000000    40.000000
mean   20.500000   6.487179    14.075000   13.500000   1.625000   352.296500
std    11.690452   4.235637     8.303189    8.857852   0.952392   377.625776
min     1.000000   1.000000     1.000000    1.000000   1.000000    19.980000
25%    10.750000   3.000000     6.750000    5.750000   1.000000    99.737500
50%    20.500000   6.000000    13.500000   11.500000   1.000000   229.985000
75%    30.250000   9.500000    20.250000   21.250000   2.000000   352.487500
max    40.000000  15.000000    29.000000   30.000000   5.000000  1599.990000

In [45]:
df.isnull().sum()

sale_id           0
date              1
store_id          1
customer_id       0
product_id        0
quantity          0
total             0
payment_method    1
dtype: int64

In [46]:
df['store_id'] = df['store_id'].fillna(df['store_id'].mean())
df['payment_method'] = df['payment_method'].ffill()

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sale_id         40 non-null     int64
 1   date            39 non-null     str
 2   store_id        40 non-null     float64
 3   customer_id     40 non-null     int64
 4   product_id      40 non-null     int64
 5   quantity        40 non-null     int64
 6   total           40 non-null     float64
 7   payment_method  40 non-null     str
dtypes: float64(2), int64(4), str(2)
memory usage: 2.6 KB

In [48]:
df['date'] = df['date'].ffill()

In [66]:
df['payment_method'] = df['payment_method'].str.title()

In [67]:
df['payment_method'].unique()

<StringArray>
['Credit Card',  'Debit Card',        'Cash',          'Cc',        'Visa',
      'Paypal',   'Apple Pay',       'Debit',          'Dc',    'Applepay',
          'Pp',      'Credit',   'Googlepay',  'Google Pay']
Length: 14, dtype: str

In [68]:
df.duplicated().sum()

np.int64(0)

In [69]:
df.drop_duplicates()

,sale_id,date,store_id,customer_id,product_id,quantity,total,payment_method
0,1,2022-01-15,3.000000,12,5,2,49.98,Credit Card
1,2,2022-01-16,1.000000,5,10,1,49.99,Credit Card
2,3,2022-01-18,2.000000,8,3,1,349.99,Debit Card
3,4,2022-01-20,4.000000,20,7,1,349.99,Cash
4,5,2022-01-22,5.000000,3,15,1,1599.99,Cc
5,6,2022-02-01,2.000000,17,1,1,899.99,Visa
6,7,2022-02-03,7.000000,25,12,2,259.98,Paypal
7,8,2022-02-05,9.000000,14,20,1,599.99,Apple Pay
8,9,2022-02-08,10.000000,6,4,1,1299.99,Debit
9,10,2022-02-10,3.000000,19,9,1,179.99,Cash
10,11,2022-02-15,6.487179,22,2,1,799.99,Credit Card
11,12,2022-02-19,5.000000,7,18,3,137.97,Dc
12,13,2022-02-22,8.000000,10,23,2,299.98,Cash
13,14,2022-03-01,12.000000,2,11,1,199.99,Credit Card
14,15,2022-03-05,15.000000,16,6,2,120.48,Debit Card
15,16,2022-03-10,1.000000,27,13,3,269.97,Paypal
16,17,2022-03-15,3.000000,9,27,1,499.99,Applepay
17,18,2022-03-20,6.000000,4,17,4,61.96,Cash
18,19,2022-03-25,9.000000,23,21,1,299.99,Credit Card
19,20,2022-04-01,11.000000,28,25,2,19.98,Credit Card
20,21,2022-04-05,13.000000,12,8,1,99.99,Debit Card
21,22,2022-04-10,2.000000,5,19,1,139.99,Pp
22,23,2022-04-15,4.000000,15,14,3,59.97,Cash
23,24,2022-04-20,7.000000,21,22,2,79.98,Credit
24,25,2022-04-25,10.000000,3,16,1,329.99,Googlepay
25,26,2022-05-01,14.000000,8,24,1,199.99,Credit Card
26,27,2022-05-05,1.000000,18,28,1,129.99,Debit Card
27,28,2022-05-10,5.000000,26,1,1,900.50,Cash
28,29,2022-05-15,9.000000,11,7,1,349.99,Paypal
29,30,2022-05-20,3.000000,24,9,2,359.98,Debit Card
30,31,2022-05-20,2.000000,13,4,1,1299.99,Credit Card
31,32,2022-06-01,6.000000,29,26,5,24.95,Cash
32,33,2022-06-05,8.000000,1,5,3,67.47,Cash
33,34,2022-06-10,11.000000,6,22,1,39.99,Debit Card
34,35,2022-06-15,4.000000,17,29,2,159.98,Credit Card
35,36,2022-06-20,7.000000,9,10,2,98.98,Cash
36,37,2022-06-25,12.000000,27,3,1,349.99,Paypal
37,38,2022-07-01,15.000000,20,11,1,199.99,Google Pay
38,39,2022-07-05,3.000000,16,30,2,499.98,Credit Card
39,40,2022-07-10,1.000000,5,3,1,349.99,Cash

In [65]:
df['sale_id'].unique

<bound method Series.unique of 0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31    32
32    33
33    34
34    35
35    36
36    37
37    38
38    39
39    40
Name: sale_id, dtype: int64>

In [61]:
df.groupby('payment_method')['total'].mean().sort_values(ascending = False)

payment_method
Cc             1599.990000
Debit          1299.990000
Visa            899.990000
Apple Pay       599.990000
Applepay        499.990000
Credit Card     357.986000
Googlepay       329.990000
Paypal          307.482500
Cash            239.378000
Google Pay      199.990000
Debit Card      183.403333
Pp              139.990000
Dc              137.970000
Credit           79.980000
Name: total, dtype: float64

In [62]:
df.duplicated().sum()

np.int64(0)